// This is the starting map

const startingMap = [
  { type: "land", classes: "land col1 row1" },
  { type: "land", classes: "land col2 row1" },
  { type: "land", classes: "land col3 row1" },
  { type: "land", classes: "land col4 row1" },
  { type: "land", classes: "land col5 row1" },
  { type: "land", classes: "land col6 row1" },
  { type: "land", classes: "land col7 row1" },
  { type: "land", classes: "land col8 row1" },
  { type: "land", classes: "land col9 row1" },
  { type: "land", classes: "land col10 row1" },
  { type: "land", classes: "land col11 row1" },
  { type: "land", classes: "land col12 row1" },
  { type: "land", classes: "land col13 row1" },
  { type: "land", classes: "land col14 row1" },
  { type: "land", classes: "land col15 row1" },
  { type: "land", classes: "land col16 row1" },
  { type: "land", classes: "land col17 row1" },
  { type: "land", classes: "land col18 row1" },
  { type: "land", classes: "land col19 row1" },
  { type: "land", classes: "land col20 row1" },
  { type: "land", classes: "land col21 row1" },
  { type: "land", classes: "land col22 row1" },
  { type: "land", classes: "land col23 row1" },
  { type: "land", classes: "land col24 row1" },
  { type: "land", classes: "land col25 row1" },
  { type: "land", classes: "land col26 row1" },
  { type: "land", classes: "land col27 row1 ocean-right" },
  { type: "ocean", classes: "ocean col28 row1" },
  { type: "ocean", classes: "ocean col29 row1" },
  { type: "ocean", classes: "ocean col30 row1" },
  { type: "ocean", classes: "ocean col31 row1" },
  { type: "ocean", classes: "ocean col32 row1" },
  { type: "ocean", classes: "ocean col33 row1" },
  { type: "land", classes: "land col1 row2" },
  { type: "land", classes: "land col2 row2" },
  { type: "land", classes: "land col3 row2" },
  { type: "land", classes: "land col4 row2" },
  { type: "land", classes: "land col5 row2" },
  { type: "land", classes: "land col6 row2" },
  { type: "land", classes: "land col7 row2" },
  { type: "land", classes: "land col8 row2" },
  { type: "land", classes: "land col9 row2" },
  { type: "land", classes: "land col10 row2" },
  { type: "land", classes: "land col11 row2" },
  { type: "land", classes: "land col12 row2" },
  { type: "land", classes: "land col13 row2" },
  { type: "land", classes: "land col14 row2" },
  { type: "land", classes: "land col15 row2" },
  { type: "land", classes: "land col16 row2" },
  { type: "land", classes: "land col17 row2" },
  { type: "land", classes: "land col18 row2" },
  { type: "land", classes: "land col19 row2" },
  { type: "land", classes: "land col20 row2" },
  { type: "land", classes: "land col21 row2" },
  { type: "land", classes: "land col22 row2" },
  { type: "land", classes: "land col23 row2" },
  { type: "land", classes: "land col24 row2" },
  { type: "land", classes: "land col25 row2" },
  { type: "land", classes: "land col26 row2" },
  { type: "land", classes: "land col27 row2 ocean-right ocean-below" },
  { type: "ocean", classes: "ocean col28 row2" },
  { type: "ocean", classes: "ocean col29 row2" },
  { type: "ocean", classes: "ocean col30 row2" },
  { type: "ocean", classes: "ocean col31 row2" },
  { type: "ocean", classes: "ocean col32 row2" },
  { type: "ocean", classes: "ocean col33 row2" },
  { type: "land", classes: "land col1 row3 " },
  { type: "land", classes: "land col2 row3 " },
  { type: "land", classes: "land col3 row3 " },
  { type: "land", classes: "land col4 row3 " },
  { type: "land", classes: "land col5 row3 " },
  { type: "land", classes: "land col6 row3 " },
  { type: "land", classes: "land col7 row3 " },
  { type: "land", classes: "land col8 row3 " },
  { type: "land", classes: "land col9 row3 " },
  { type: "land", classes: "land col10 row3 " },
  { type: "land", classes: "land col11 row3 " },
  { type: "land", classes: "land col12 row3 " },
  { type: "land", classes: "land col13 row3 " },
  { type: "land", classes: "land col14 row3 " },
  { type: "land", classes: "land col15 row3 " },
  { type: "land", classes: "land col16 row3 " },
  { type: "land", classes: "land col17 row3 " },
  { type: "land", classes: "land col18 row3 " },
  { type: "land", classes: "land col19 row3 " },
  { type: "land", classes: "land col20 row3 " },
  { type: "land", classes: "land col21 row3 " },
  { type: "land", classes: "land col22 row3 " },
  { type: "land", classes: "land col23 row3 " },
  { type: "land", classes: "land col24 row3 " },
  { type: "land", classes: "land col25 row3 " },
  { type: "land", classes: "land col26 row3 ocean-right ocean-below" },
  { type: "ocean", classes: "ocean col27 row3 " },
  { type: "ocean", classes: "ocean col28 row3" },
  { type: "ocean", classes: "ocean col29 row3" },
  { type: "ocean", classes: "ocean col30 row3" },
  { type: "ocean", classes: "ocean col31 row3" },
  { type: "ocean", classes: "ocean col32 row3" },
  { type: "ocean", classes: "ocean col33 row3" },
  { type: "land", classes: "land col1 row4 " },
  { type: "land", classes: "land col2 row4 " },
  { type: "land", classes: "land col3 row4 " },
  { type: "land", classes: "land col4 row4 " },
  { type: "land", classes: "land col5 row4 " },
  { type: "land", classes: "land col6 row4 " },
  { type: "land", classes: "land col7 row4 " },
  { type: "land", classes: "land col8 row4 " },
  { type: "land", classes: "land col9 row4 " },
  { type: "land", classes: "land col10 row4 " },
  { type: "land", classes: "land col11 row4 " },
  { type: "land", classes: "land col12 row4 " },
  { type: "land", classes: "land col13 row4 " },
  { type: "land", classes: "land col14 row4 " },
  { type: "land", classes: "land col15 row4 " },
  { type: "land", classes: "land col16 row4 " },
  { type: "land", classes: "land col17 row4 " },
  { type: "land", classes: "land col18 row4 " },
  { type: "land", classes: "land col19 row4 " },
  { type: "land", classes: "land col20 row4 " },
  { type: "land", classes: "land col21 row4 " },
  { type: "land", classes: "land col22 row4 " },
  { type: "land", classes: "land col23 row4 " },
  { type: "land", classes: "land col24 row4 " },
  { type: "land", classes: "land col25 row4 ocean-right ocean-below" },
  { type: "ocean", classes: "ocean col26 row4 " },
  { type: "ocean", classes: "ocean col27 row4" },
  { type: "ocean", classes: "ocean col28 row4" },
  { type: "ocean", classes: "ocean col29 row4" },
  { type: "ocean", classes: "ocean col30 row4" },
  { type: "ocean", classes: "ocean col31 row4" },
  { type: "ocean", classes: "ocean col32 row4" },
  { type: "ocean", classes: "ocean col33 row4" },
  { type: "land", classes: "land col1 row5 " },
  { type: "land", classes: "land col2 row5 " },
  { type: "land", classes: "land col3 row5 " },
  { type: "land", classes: "land col4 row5 " },
  { type: "land", classes: "land col5 row5 " },
  { type: "land", classes: "land col6 row5 " },
  { type: "land", classes: "land col7 row5 " },
  { type: "land", classes: "land col8 row5 " },
  { type: "land", classes: "land col9 row5 " },
  { type: "land", classes: "land col10 row5 " },
  { type: "land", classes: "land col11 row5 " },
  { type: "land", classes: "land col12 row5 " },
  { type: "land", classes: "land col13 row5 " },
  { type: "land", classes: "land col14 row5 " },
  { type: "land", classes: "land col15 row5 " },
  { type: "land", classes: "land col16 row5 " },
  { type: "land", classes: "land col17 row5 " },
  { type: "land", classes: "land col18 row5 " },
  { type: "land", classes: "land col19 row5 " },
  { type: "land", classes: "land col20 row5 " },
  { type: "land", classes: "land col21 row5 " },
  { type: "land", classes: "land col22 row5 " },
  { type: "land", classes: "land col23 row5 " },
  { type: "land", classes: "land col24 row5 ocean-right ocean-below" },
  { type: "ocean", classes: "ocean col25 row5 " },
  { type: "ocean", classes: "ocean col26 row5" },
  { type: "ocean", classes: "ocean col27 row5" },
  { type: "ocean", classes: "ocean col28 row5" },
  { type: "ocean", classes: "ocean col29 row5" },
  { type: "ocean", classes: "ocean col30 row5" },
  { type: "ocean", classes: "ocean col31 row5" },
  { type: "ocean", classes: "ocean col32 row5" },
  { type: "ocean", classes: "ocean col33 row5" },
  { type: "land", classes: "land col1 row6  border-south" },
  { type: "land", classes: "land col2 row6 " },
  { type: "land", classes: "land col3 row6 " },
  { type: "land", classes: "land col4 row6 " },
  { type: "land", classes: "land col5 row6 " },
  { type: "land", classes: "land col6 row6 " },
  { type: "land", classes: "land col7 row6 " },
  { type: "land", classes: "land col8 row6 " },
  { type: "land", classes: "land col9 row6 " },
  { type: "land", classes: "land col10 row6 " },
  { type: "land", classes: "land col11 row6 " },
  { type: "land", classes: "land col12 row6 " },
  { type: "land", classes: "land col13 row6 " },
  { type: "land", classes: "land col14 row6 " },
  { type: "land", classes: "land col15 row6 " },
  { type: "land", classes: "land col16 row6 " },
  { type: "land", classes: "land col17 row6 " },
  { type: "land", classes: "land col18 row6 " },
  { type: "land", classes: "land col19 row6 " },
  { type: "land", classes: "land col20 row6 " },
  { type: "land", classes: "land col21 row6 " },
  { type: "land", classes: "land col22 row6 " },
  { type: "land", classes: "land col23 row6 ocean-right" },
  { type: "ocean", classes: "ocean col24 row6 " },
  { type: "ocean", classes: "ocean col25 row6" },
  { type: "ocean", classes: "ocean col26 row6" },
  { type: "ocean", classes: "ocean col27 row6" },
  { type: "ocean", classes: "ocean col28 row6" },
  { type: "ocean", classes: "ocean col29 row6" },
  { type: "ocean", classes: "ocean col30 row6" },
  { type: "ocean", classes: "ocean col31 row6" },
  { type: "ocean", classes: "ocean col32 row6" },
  { type: "ocean", classes: "ocean col33 row6" },
  { type: "land", classes: "land col1 row7 " },
  { type: "land", classes: "land col2 row7  border-south border-west" },
  { type: "land", classes: "land col3 row7 " },
  { type: "land", classes: "land col4 row7 " },
  { type: "land", classes: "land col5 row7 " },
  { type: "land", classes: "land col6 row7 " },
  { type: "land", classes: "land col7 row7 " },
  { type: "land", classes: "land col8 row7 " },
  { type: "land", classes: "land col9 row7 " },
  { type: "land", classes: "land col10 row7 " },
  { type: "land", classes: "land col11 row7 " },
  { type: "land", classes: "land col12 row7 " },
  { type: "land", classes: "land col13 row7 " },
  { type: "land", classes: "land col14 row7 " },
  { type: "land", classes: "land col15 row7 " },
  { type: "land", classes: "land col16 row7 ocean-below" },
  { type: "land", classes: "land col17 row7 ocean-below" },
  { type: "land", classes: "land col18 row7 ocean-below" },
  { type: "land", classes: "land col19 row7 " },
  { type: "land", classes: "land col20 row7 ocean-below" },
  { type: "land", classes: "land col21 row7 ocean-below" },
  { type: "land", classes: "land col22 row7 " },
  { type: "land", classes: "land col23 row7 ocean-right" },
  { type: "ocean", classes: "ocean col24 row7 " },
  { type: "ocean", classes: "ocean col25 row7" },
  { type: "ocean", classes: "ocean col26 row7" },
  { type: "ocean", classes: "ocean col27 row7" },
  { type: "ocean", classes: "ocean col28 row7" },
  { type: "ocean", classes: "ocean col29 row7" },
  { type: "ocean", classes: "ocean col30 row7" },
  { type: "ocean", classes: "ocean col31 row7" },
  { type: "ocean", classes: "ocean col32 row7" },
  { type: "ocean", classes: "ocean col33 row7" },
  { type: "land", classes: "land col1 row8 " },
  { type: "land", classes: "land col2 row8 " },
  { type: "land", classes: "land col3 row8  border-south border-west" },
  { type: "land", classes: "land col4 row8 " },
  { type: "land", classes: "land col5 row8  border-south" },
  { type: "land", classes: "land col6 row8  border-south" },
  { type: "land", classes: "land col7 row8 " },
  { type: "land", classes: "land col8 row8 " },
  { type: "land", classes: "land col9 row8 " },
  { type: "land", classes: "land col10 row8 " },
  { type: "land", classes: "land col11 row8 " },
  { type: "land", classes: "land col12 row8 ocean-below" },
  { type: "land", classes: "land col13 row8 ocean-below" },
  { type: "land", classes: "land col14 row8 ocean-below" },
  {
    type: "land",
    classes: "land col15 row8 ocean-right ocean-below"
  },
  { type: "ocean", classes: "ocean col16 row8 " },
  { type: "ocean", classes: "ocean col17 row8 " },
  { type: "ocean", classes: "ocean col18 row8" },
  {
    type: "land",
    classes: "land col19 row8 ocean-right ocean-below ocean-left"
  },
  { type: "ocean", classes: "ocean col20 row8 " },
  { type: "ocean", classes: "ocean col21 row8 " },
  { type: "land", classes: "land col22 row8 ocean-left" },
  { type: "land", classes: "land col23 row8 ocean-right" },
  { type: "ocean", classes: "ocean col24 row8 " },
  { type: "ocean", classes: "ocean col25 row8" },
  { type: "ocean", classes: "ocean col26 row8" },
  { type: "ocean", classes: "ocean col27 row8" },
  { type: "ocean", classes: "ocean col28 row8" },
  { type: "ocean", classes: "ocean col29 row8" },
  { type: "ocean", classes: "ocean col30 row8" },
  { type: "ocean", classes: "ocean col31 row8" },
  { type: "ocean", classes: "ocean col32 row8" },
  { type: "ocean", classes: "ocean col33 row8" },
  { type: "land", classes: "land col1 row9 " },
  { type: "land", classes: "land col2 row9 " },
  { type: "land", classes: "land col3 row9 " },
  {
    type: "land",
    classes: "land col4 row9  border-south border-west border-east"
  },
  { type: "land", classes: "land col5 row9 " },
  { type: "land", classes: "land col6 row9 " },
  { type: "land", classes: "land col7 row9  border-west" },
  { type: "land", classes: "land col8 row9 " },
  { type: "land", classes: "land col9 row9 " },
  { type: "land", classes: "land col10 row9 " },
  { type: "land", classes: "land col11 row9 ocean-right ocean-below" },
  { type: "ocean", classes: "ocean col12 row9 " },
  { type: "ocean", classes: "ocean col13 row9 " },
  { type: "ocean", classes: "ocean col14 row9 " },
  { type: "ocean", classes: "ocean col15 row9 " },
  { type: "ocean", classes: "ocean col16 row9" },
  { type: "ocean", classes: "ocean col17 row9" },
  { type: "ocean", classes: "ocean col18 row9" },
  { type: "ocean", classes: "ocean col19 row9 " },
  { type: "ocean", classes: "ocean col20 row9" },
  { type: "ocean", classes: "ocean col21 row9 " },
  { type: "land", classes: "land col22 row9 ocean-left" },
  { type: "land", classes: "land col23 row9 ocean-right" },
  { type: "ocean", classes: "ocean col24 row9 " },
  { type: "ocean", classes: "ocean col25 row9" },
  { type: "ocean", classes: "ocean col26 row9" },
  { type: "ocean", classes: "ocean col27 row9" },
  { type: "ocean", classes: "ocean col28 row9" },
  { type: "ocean", classes: "ocean col29 row9" },
  { type: "ocean", classes: "ocean col30 row9" },
  { type: "ocean", classes: "ocean col31 row9" },
  { type: "ocean", classes: "ocean col32 row9" },
  { type: "ocean", classes: "ocean col33 row9" },
  { type: "land", classes: "land col1 row10 " },
  { type: "land", classes: "land col2 row10" },
  { type: "land", classes: "land col3 row10 " },
  { type: "land", classes: "land col4 row10 " },
  { type: "land", classes: "land col5 row10 " },
  { type: "land", classes: "land col6 row10 " },
  { type: "land", classes: "land col7 row10  border-south border-west" },
  { type: "land", classes: "land col8 row10 " },
  { type: "land", classes: "land col9 row10 " },
  {
    type: "land",
    classes: "land col10 row10 ocean-right ocean-below"
  },
  { type: "ocean", classes: "ocean col11 row10 " },
  { type: "ocean", classes: "ocean col12 row10" },
  { type: "ocean", classes: "ocean col13 row10" },
  { type: "ocean", classes: "ocean col14 row10" },
  { type: "ocean", classes: "ocean col15 row10" },
  { type: "ocean", classes: "ocean col16 row10" },
  { type: "ocean", classes: "ocean col17 row10" },
  { type: "ocean", classes: "ocean col18 row10" },
  { type: "ocean", classes: "ocean col19 row10" },
  { type: "ocean", classes: "ocean col20 row10" },
  { type: "ocean", classes: "ocean col21 row10 " },
  { type: "land", classes: "land col22 row10 ocean-below ocean-left" },
  { type: "land", classes: "land col23 row10 ocean-right" },
  { type: "ocean", classes: "ocean col24 row10 " },
  { type: "ocean", classes: "ocean col25 row10" },
  { type: "ocean", classes: "ocean col26 row10" },
  { type: "ocean", classes: "ocean col27 row10" },
  { type: "ocean", classes: "ocean col28 row10" },
  { type: "ocean", classes: "ocean col29 row10" },
  { type: "ocean", classes: "ocean col30 row10" },
  { type: "ocean", classes: "ocean col31 row10" },
  { type: "ocean", classes: "ocean col32 row10" },
  { type: "ocean", classes: "ocean col33 row10" },
  { type: "land", classes: "land col1 row11 " },
  { type: "land", classes: "land col2 row11" },
  { type: "land", classes: "land col3 row11 " },
  { type: "land", classes: "land col4 row11 " },
  { type: "land", classes: "land col5 row11 " },
  { type: "land", classes: "land col6 row11 " },
  { type: "land", classes: "land col7 row11 " },
  { type: "land", classes: "land col8 row11  border-south border-west" },
  {
    type: "land",
    classes: "land col9 row11 ocean-right"
  },
  { type: "ocean", classes: "ocean col10 row11 " },
  { type: "ocean", classes: "ocean col11 row11" },
  { type: "ocean", classes: "ocean col12 row11" },
  { type: "ocean", classes: "ocean col13 row11" },
  { type: "ocean", classes: "ocean col14 row11" },
  { type: "ocean", classes: "ocean col15 row11" },
  { type: "ocean", classes: "ocean col16 row11" },
  { type: "ocean", classes: "ocean col17 row11" },
  { type: "ocean", classes: "ocean col18 row11" },
  { type: "ocean", classes: "ocean col19 row11" },
  { type: "ocean", classes: "ocean col20 row11" },
  { type: "ocean", classes: "ocean col21 row11" },
  { type: "ocean", classes: "ocean col22 row11 " },
  { type: "land", classes: "land col23 row11 ocean-left" },
  { type: "land", classes: "land col24 row11 ocean-above ocean-right" },
  { type: "ocean", classes: "ocean col25 row11 " },
  { type: "ocean", classes: "ocean col26 row11" },
  { type: "ocean", classes: "ocean col27 row11" },
  { type: "ocean", classes: "ocean col28 row11" },
  { type: "ocean", classes: "ocean col29 row11" },
  { type: "ocean", classes: "ocean col30 row11" },
  { type: "ocean", classes: "ocean col31 row11" },
  { type: "ocean", classes: "ocean col32 row11" },
  { type: "ocean", classes: "ocean col33 row11" },
  { type: "land", classes: "land col1 row12 " },
  { type: "land", classes: "land col2 row12" },
  { type: "land", classes: "land col3 row12 " },
  { type: "land", classes: "land col4 row12 " },
  { type: "land", classes: "land col5 row12 " },
  { type: "land", classes: "land col6 row12 " },
  { type: "land", classes: "land col7 row12 " },
  { type: "land", classes: "land col8 row12 " },
  {
    type: "land",
    classes: "land col9 row12 ocean-right border-south border-west"
  },
  { type: "ocean", classes: "ocean col10 row12 " },
  { type: "ocean", classes: "ocean col11 row12" },
  { type: "ocean", classes: "ocean col12 row12" },
  { type: "ocean", classes: "ocean col13 row12" },
  { type: "ocean", classes: "ocean col14 row12" },
  { type: "ocean", classes: "ocean col15 row12" },
  { type: "ocean", classes: "ocean col16 row12" },
  { type: "ocean", classes: "ocean col17 row12" },
  { type: "ocean", classes: "ocean col18 row12" },
  { type: "ocean", classes: "ocean col19 row12" },
  { type: "ocean", classes: "ocean col20 row12" },
  { type: "ocean", classes: "ocean col21 row12" },
  { type: "ocean", classes: "ocean col22 row12 " },
  { type: "land", classes: "land col23 row12 ocean-below ocean-left" },
  {
    type: "land",
    classes: "land col24 row12 ocean-right ocean-below"
  },
  { type: "ocean", classes: "ocean col25 row12 " },
  { type: "ocean", classes: "ocean col26 row12" },
  { type: "ocean", classes: "ocean col27 row12" },
  { type: "ocean", classes: "ocean col28 row12" },
  { type: "ocean", classes: "ocean col29 row12" },
  { type: "ocean", classes: "ocean col30 row12" },
  { type: "ocean", classes: "ocean col31 row12" },
  { type: "ocean", classes: "ocean col32 row12" },
  { type: "ocean", classes: "ocean col33 row12" },
  { type: "land", classes: "land col1 row13 ocean-below" },
  { type: "land", classes: "land col2 row13" },
  { type: "land", classes: "land col3 row13 " },
  { type: "land", classes: "land col4 row13 " },
  { type: "land", classes: "land col5 row13 " },
  { type: "land", classes: "land col6 row13 " },
  { type: "land", classes: "land col7 row13 " },
  { type: "land", classes: "land col8 row13 " },
  { type: "land", classes: "land col9 row13 ocean-right" },
  { type: "ocean", classes: "ocean col10 row13 " },
  { type: "ocean", classes: "ocean col11 row13" },
  { type: "ocean", classes: "ocean col12 row13" },
  { type: "ocean", classes: "ocean col13 row13" },
  { type: "ocean", classes: "ocean col14 row13" },
  { type: "ocean", classes: "ocean col15 row13" },
  { type: "ocean", classes: "ocean col16 row13" },
  { type: "ocean", classes: "ocean col17 row13" },
  { type: "ocean", classes: "ocean col18 row13" },
  { type: "ocean", classes: "ocean col19 row13" },
  { type: "ocean", classes: "ocean col20 row13" },
  { type: "ocean", classes: "ocean col21 row13" },
  { type: "ocean", classes: "ocean col22 row13" },
  { type: "ocean", classes: "ocean col23 row13 " },
  { type: "ocean", classes: "ocean col24 row13 " },
  { type: "ocean", classes: "ocean col25 row13" },
  { type: "ocean", classes: "ocean col26 row13" },
  { type: "ocean", classes: "ocean col27 row13" },
  { type: "ocean", classes: "ocean col28 row13" },
  { type: "ocean", classes: "ocean col29 row13" },
  { type: "ocean", classes: "ocean col30 row13" },
  { type: "ocean", classes: "ocean col31 row13" },
  { type: "ocean", classes: "ocean col32 row13" },
  { type: "ocean", classes: "ocean col33 row13" },
  { type: "ocean", classes: "ocean col1 row14 " },
  { type: "land", classes: "land col2 row14 ocean-left" },
  { type: "land", classes: "land col3 row14 " },
  { type: "land", classes: "land col4 row14 " },
  { type: "land", classes: "land col5 row14 " },
  { type: "land", classes: "land col6 row14 " },
  { type: "land", classes: "land col7 row14 " },
  { type: "land", classes: "land col8 row14 " },
  { type: "land", classes: "land col9 row14 ocean-right" },
  { type: "ocean", classes: "ocean col10 row14 " },
  { type: "ocean", classes: "ocean col11 row14" },
  { type: "ocean", classes: "ocean col12 row14" },
  { type: "ocean", classes: "ocean col13 row14" },
  { type: "ocean", classes: "ocean col14 row14" },
  { type: "ocean", classes: "ocean col15 row14" },
  { type: "ocean", classes: "ocean col16 row14" },
  { type: "ocean", classes: "ocean col17 row14" },
  {
    type: "ocean",
    classes: "ocean col18 row14"
  },
  { type: "ocean", classes: "ocean col19 row14" },
  { type: "ocean", classes: "ocean col20 row14" },
  { type: "ocean", classes: "ocean col21 row14" },
  { type: "ocean", classes: "ocean col22 row14" },
  { type: "ocean", classes: "ocean col23 row14" },
  { type: "ocean", classes: "ocean col24 row14" },
  { type: "ocean", classes: "ocean col25 row14" },
  { type: "ocean", classes: "ocean col26 row14" },
  { type: "ocean", classes: "ocean col27 row14" },
  { type: "ocean", classes: "ocean col28 row14" },
  { type: "ocean", classes: "ocean col29 row14" },
  { type: "ocean", classes: "ocean col30 row14" },
  { type: "ocean", classes: "ocean col31 row14" },
  { type: "ocean", classes: "ocean col32 row14" },
  { type: "ocean", classes: "ocean col33 row14" },
  { type: "ocean", classes: "ocean col1 row15 " },
  { type: "land", classes: "land col2 row15 ocean-below ocean-left" },
  { type: "land", classes: "land col3 row15 " },
  { type: "land", classes: "land col4 row15 " },
  { type: "land", classes: "land col5 row15 " },
  { type: "land", classes: "land col6 row15 " },
  { type: "land", classes: "land col7 row15 " },
  { type: "land", classes: "land col8 row15 " },
  { type: "land", classes: "land col9 row15 ocean-right" },
  { type: "ocean", classes: "ocean col10 row15 " },
  { type: "ocean", classes: "ocean col11 row15" },
  { type: "ocean", classes: "ocean col12 row15" },
  { type: "ocean", classes: "ocean col13 row15" },
  { type: "ocean", classes: "ocean col14 row15" },
  { type: "ocean", classes: "ocean col15 row15" },
  { type: "ocean", classes: "ocean col16 row15" },
  { type: "ocean", classes: "ocean col17 row15" },
  { type: "ocean", classes: "ocean col18 row15" },
  { type: "ocean", classes: "ocean col19 row15" },
  { type: "ocean", classes: "ocean col20 row15" },
  { type: "ocean", classes: "ocean col21 row15" },
  { type: "ocean", classes: "ocean col22 row15 " },
  { type: "ocean", classes: "ocean col23 row15 " },
  { type: "ocean", classes: "ocean col24 row15 " },
  { type: "ocean", classes: "ocean col25 row15 " },
  { type: "ocean", classes: "ocean col26 row15 " },
  { type: "ocean", classes: "ocean col27 row15" },
  { type: "ocean", classes: "ocean col28 row15" },
  { type: "ocean", classes: "ocean col29 row15" },
  { type: "ocean", classes: "ocean col30 row15" },
  { type: "ocean", classes: "ocean col31 row15" },
  { type: "ocean", classes: "ocean col32 row15" },
  { type: "ocean", classes: "ocean col33 row15" },
  { type: "ocean", classes: "ocean col1 row16" },
  { type: "ocean", classes: "ocean col2 row16 " },
  { type: "land", classes: "land col3 row16 ocean-left" },
  { type: "land", classes: "land col4 row16 " },
  { type: "land", classes: "land col5 row16 " },
  { type: "land", classes: "land col6 row16 " },
  { type: "land", classes: "land col7 row16 " },
  { type: "land", classes: "land col8 row16 " },
  { type: "land", classes: "land col9 row16 ocean-right" },
  { type: "ocean", classes: "ocean col10 row16 " },
  { type: "ocean", classes: "ocean col11 row16" },
  { type: "ocean", classes: "ocean col12 row16" },
  { type: "ocean", classes: "ocean col13 row16" },
  { type: "ocean", classes: "ocean col14 row16" },
  { type: "ocean", classes: "ocean col15 row16" },
  { type: "ocean", classes: "ocean col16 row16" },
  { type: "ocean", classes: "ocean col17 row16" },
  { type: "ocean", classes: "ocean col18 row16" },
  { type: "ocean", classes: "ocean col19 row16" },
  { type: "ocean", classes: "ocean col20 row16" },
  { type: "ocean", classes: "ocean col21 row16 " },
  { type: "ocean", classes: "ocean col22 row16 " },
  { type: "ocean", classes: "ocean col23 row16 " },
  { type: "ocean", classes: "ocean col24 row16 " },
  { type: "ocean", classes: "ocean col25 row16 " },
  { type: "ocean", classes: "ocean col26 row16 " },
  { type: "ocean", classes: "ocean col27 row16 " },
  { type: "ocean", classes: "ocean col28 row16 " },
  { type: "ocean", classes: "ocean col29 row16" },
  { type: "ocean", classes: "ocean col30 row16" },
  { type: "ocean", classes: "ocean col31 row16" },
  { type: "ocean", classes: "ocean col32 row16" },
  { type: "ocean", classes: "ocean col33 row16" },
  { type: "ocean", classes: "ocean col1 row17" },
  { type: "ocean", classes: "ocean col2 row17 " },
  { type: "land", classes: "land col3 row17 ocean-left" },
  { type: "land", classes: "land col4 row17 " },
  { type: "land", classes: "land col5 row17 " },
  { type: "land", classes: "land col6 row17 " },
  { type: "land", classes: "land col7 row17 " },
  { type: "land", classes: "land col8 row17 " },
  { type: "land", classes: "land col9 row17 ocean-right" },
  { type: "ocean", classes: "ocean col10 row17 " },
  { type: "ocean", classes: "ocean col11 row17" },
  { type: "ocean", classes: "ocean col12 row17" },
  { type: "ocean", classes: "ocean col13 row17" },
  { type: "ocean", classes: "ocean col14 row17" },
  { type: "ocean", classes: "ocean col15 row17" },
  { type: "ocean", classes: "ocean col16 row17 " },
  { type: "ocean", classes: "ocean col17 row17 " },
  { type: "ocean", classes: "ocean col18 row17" },
  { type: "ocean", classes: "ocean col19 row17" },
  { type: "ocean", classes: "ocean col20 row17 " },
  { type: "ocean", classes: "ocean col21 row17 " },
  { type: "ocean", classes: "ocean col22 row17 " },
  { type: "land", classes: "land col23 row17 ocean-above ocean-left" },
  { type: "land", classes: "land col24 row17 ocean-above" },
  { type: "land", classes: "land col25 row17 ocean-above ocean-below" },
  { type: "land", classes: "land col26 row17 ocean-above" },
  { type: "land", classes: "land col27 row17 ocean-above ocean-right" },
  { type: "ocean", classes: "ocean col28 row17 " },
  { type: "ocean", classes: "ocean col29 row17 " },
  { type: "ocean", classes: "ocean col30 row17" },
  { type: "ocean", classes: "ocean col31 row17" },
  { type: "ocean", classes: "ocean col32 row17" },
  { type: "ocean", classes: "ocean col33 row17" },
  { type: "ocean", classes: "ocean col1 row18" },
  { type: "ocean", classes: "ocean col2 row18 " },
  { type: "land", classes: "land col3 row18 ocean-below ocean-left" },
  { type: "land", classes: "land col4 row18 " },
  { type: "land", classes: "land col5 row18 " },
  { type: "land", classes: "land col6 row18 " },
  { type: "land", classes: "land col7 row18 " },
  { type: "land", classes: "land col8 row18 " },
  { type: "land", classes: "land col9 row18 " },
  { type: "land", classes: "land col10 row18 ocean-above ocean-right" },
  { type: "ocean", classes: "ocean col11 row18 " },
  { type: "ocean", classes: "ocean col12 row18" },
  { type: "ocean", classes: "ocean col13 row18" },
  { type: "ocean", classes: "ocean col14 row18" },
  { type: "ocean", classes: "ocean col15 row18 " },
  { type: "ocean", classes: "ocean col16 row18 " },
  { type: "ocean", classes: "ocean col17 row18 " },
  { type: "ocean", classes: "ocean col18 row18 " },
  { type: "ocean", classes: "ocean col19 row18" },
  { type: "ocean", classes: "ocean col20 row18 " },
  { type: "ocean", classes: "ocean col21 row18 " },
  {
    type: "land",
    classes: "land col22 row18 ocean-above ocean-below ocean-left"
  },
  { type: "land", classes: "land col23 row18 ocean-below" },
  { type: "land", classes: "land col24 row18 ocean-right ocean-below" },
  { type: "ocean", classes: "ocean col25 row18 " },
  { type: "land", classes: "land col26 row18 ocean-below ocean-left" },
  { type: "land", classes: "land col27 row18 ocean-below" },
  { type: "land", classes: "land col28 row18 ocean-above ocean-below" },
  {
    type: "land",
    classes: "land col29 row18 ocean-above ocean-right ocean-below"
  },
  { type: "ocean", classes: "ocean col30 row18 " },
  { type: "ocean", classes: "ocean col31 row18" },
  { type: "ocean", classes: "ocean col32 row18 " },
  { type: "ocean", classes: "ocean col33 row18" },
  { type: "ocean", classes: "ocean col1 row19" },
  { type: "ocean", classes: "ocean col2 row19" },
  { type: "ocean", classes: "ocean col3 row19 " },
  { type: "land", classes: "land col4 row19 ocean-below ocean-left" },
  { type: "land", classes: "land col5 row19 " },
  { type: "land", classes: "land col6 row19 " },
  { type: "land", classes: "land col7 row19 " },
  { type: "land", classes: "land col8 row19 " },
  { type: "land", classes: "land col9 row19 " },
  { type: "land", classes: "land col10 row19 ocean-right" },
  { type: "ocean", classes: "ocean col11 row19 " },
  { type: "ocean", classes: "ocean col12 row19 " },
  { type: "ocean", classes: "ocean col13 row19" },
  { type: "ocean", classes: "ocean col14 row19" },
  { type: "ocean", classes: "ocean col15 row19 " },
  { type: "land", classes: "land col16 row19 ocean-above ocean-left" },
  { type: "land", classes: "land col17 row19 ocean-above ocean-right" },
  { type: "ocean", classes: "ocean col18 row19 " },
  { type: "ocean", classes: "ocean col19 row19" },
  { type: "ocean", classes: "ocean col20 row19" },
  { type: "ocean", classes: "ocean col21 row19 " },
  { type: "ocean", classes: "ocean col22 row19 " },
  { type: "ocean", classes: "ocean col23 row19 " },
  { type: "ocean", classes: "ocean col24 row19 " },
  { type: "ocean", classes: "ocean col25 row19 " },
  { type: "ocean", classes: "ocean col26 row19 " },
  { type: "ocean", classes: "ocean col27 row19 " },
  { type: "ocean", classes: "ocean col28 row19 " },
  { type: "ocean", classes: "ocean col29 row19 " },
  { type: "ocean", classes: "ocean col30 row19 " },
  { type: "ocean", classes: "ocean col31 row19 " },
  {
    type: "land",
    classes: "land col32 row19 ocean-above ocean-right ocean-left"
  },
  { type: "ocean", classes: "ocean col33 row19 " },
  { type: "ocean", classes: "ocean col1 row20" },
  { type: "ocean", classes: "ocean col2 row20" },
  { type: "ocean", classes: "ocean col3 row20" },
  { type: "ocean", classes: "ocean col4 row20 " },
  { type: "land", classes: "land col5 row20 ocean-below ocean-left" },
  { type: "land", classes: "land col6 row20 ocean-below" },
  { type: "land", classes: "land col7 row20 " },
  { type: "land", classes: "land col8 row20 " },
  { type: "land", classes: "land col9 row20 " },
  { type: "land", classes: "land col10 row20 " },
  { type: "land", classes: "land col11 row20 ocean-above" },
  { type: "land", classes: "land col12 row20 ocean-above ocean-right" },
  { type: "ocean", classes: "ocean col13 row20 " },
  { type: "ocean", classes: "ocean col14 row20 " },
  { type: "land", classes: "land col15 row20 ocean-above ocean-left" },
  { type: "land", classes: "land col16 row20 " },
  { type: "land", classes: "land col17 row20 ocean-right" },
  { type: "ocean", classes: "ocean col18 row20 " },
  { type: "ocean", classes: "ocean col19 row20" },
  { type: "ocean", classes: "ocean col20 row20" },
  { type: "ocean", classes: "ocean col21 row20" },
  { type: "ocean", classes: "ocean col22 row20" },
  { type: "ocean", classes: "ocean col23 row20" },
  { type: "ocean", classes: "ocean col24 row20" },
  { type: "ocean", classes: "ocean col25 row20" },
  { type: "ocean", classes: "ocean col26 row20 " },
  { type: "ocean", classes: "ocean col27 row20 " },
  { type: "ocean", classes: "ocean col28 row20 " },
  { type: "ocean", classes: "ocean col29 row20 " },
  { type: "ocean", classes: "ocean col30 row20 " },
  {
    type: "land",
    classes: "land col31 row20 ocean-above ocean-below ocean-left"
  },
  { type: "land", classes: "land col32 row20 ocean-right ocean-below" },
  { type: "ocean", classes: "ocean col33 row20 " },
  { type: "ocean", classes: "ocean col1 row21" },
  { type: "ocean", classes: "ocean col2 row21" },
  { type: "ocean", classes: "ocean col3 row21" },
  { type: "ocean", classes: "ocean col4 row21" },
  { type: "ocean", classes: "ocean col5 row21 " },
  { type: "ocean", classes: "ocean col6 row21 " },
  { type: "land", classes: "land col7 row21 ocean-below ocean-left" },
  { type: "land", classes: "land col8 row21 " },
  { type: "land", classes: "land col9 row21 " },
  { type: "land", classes: "land col10 row21 " },
  { type: "land", classes: "land col11 row21 " },
  { type: "land", classes: "land col12 row21 " },
  { type: "land", classes: "land col13 row21 ocean-above" },
  { type: "land", classes: "land col14 row21 ocean-above" },
  { type: "land", classes: "land col15 row21 " },
  { type: "land", classes: "land col16 row21 " },
  { type: "land", classes: "land col17 row21 ocean-right" },
  { type: "ocean", classes: "ocean col18 row21 " },
  { type: "ocean", classes: "ocean col19 row21" },
  { type: "ocean", classes: "ocean col20 row21" },
  { type: "ocean", classes: "ocean col21 row21" },
  { type: "ocean", classes: "ocean col22 row21" },
  { type: "ocean", classes: "ocean col23 row21" },
  { type: "ocean", classes: "ocean col24 row21" },
  { type: "ocean", classes: "ocean col25 row21 " },
  {
    type: "land",
    classes: "land col26 row21 ocean-above ocean-right ocean-below ocean-left"
  },
  { type: "ocean", classes: "ocean col27 row21 " },
  { type: "ocean", classes: "ocean col28 row21" },
  { type: "ocean", classes: "ocean col29 row21" },
  { type: "ocean", classes: "ocean col30 row21" },
  { type: "ocean", classes: "ocean col31 row21 " },
  { type: "ocean", classes: "ocean col32 row21 " },
  { type: "ocean", classes: "ocean col33 row21" },
  { type: "ocean", classes: "ocean col1 row22" },
  { type: "ocean", classes: "ocean col2 row22" },
  { type: "ocean", classes: "ocean col3 row22" },
  { type: "ocean", classes: "ocean col4 row22" },
  { type: "ocean", classes: "ocean col5 row22" },
  { type: "ocean", classes: "ocean col6 row22" },
  { type: "ocean", classes: "ocean col7 row22 " },
  { type: "land", classes: "land col8 row22 ocean-below ocean-left" },
  { type: "land", classes: "land col9 row22 ocean-below" },
  { type: "land", classes: "land col10 row22 ocean-below" },
  { type: "land", classes: "land col11 row22 ocean-below" },
  { type: "land", classes: "land col12 row22 ocean-below" },
  { type: "land", classes: "land col13 row22 " },
  { type: "land", classes: "land col14 row22 " },
  { type: "land", classes: "land col15 row22 " },
  { type: "land", classes: "land col16 row22 " },
  { type: "land", classes: "land col17 row22 ocean-right" },
  { type: "ocean", classes: "ocean col18 row22 " },
  { type: "ocean", classes: "ocean col19 row22 " },
  { type: "ocean", classes: "ocean col20 row22 " },
  { type: "ocean", classes: "ocean col21 row22 " },
  { type: "ocean", classes: "ocean col22 row22" },
  { type: "ocean", classes: "ocean col23 row22" },
  { type: "ocean", classes: "ocean col24 row22" },
  { type: "ocean", classes: "ocean col25 row22" },
  { type: "ocean", classes: "ocean col26 row22 " },
  { type: "ocean", classes: "ocean col27 row22" },
  { type: "ocean", classes: "ocean col28 row22" },
  { type: "ocean", classes: "ocean col29 row22" },
  { type: "ocean", classes: "ocean col30 row22" },
  { type: "ocean", classes: "ocean col31 row22" },
  { type: "ocean", classes: "ocean col32 row22" },
  { type: "ocean", classes: "ocean col33 row22" },
  { type: "ocean", classes: "ocean col1 row23" },
  { type: "ocean", classes: "ocean col2 row23" },
  { type: "ocean", classes: "ocean col3 row23" },
  { type: "ocean", classes: "ocean col4 row23" },
  { type: "ocean", classes: "ocean col5 row23" },
  { type: "ocean", classes: "ocean col6 row23" },
  { type: "ocean", classes: "ocean col7 row23" },
  { type: "ocean", classes: "ocean col8 row23 " },
  { type: "ocean", classes: "ocean col9 row23 " },
  { type: "ocean", classes: "ocean col10 row23 " },
  { type: "ocean", classes: "ocean col11 row23 " },
  { type: "ocean", classes: "ocean col12 row23 " },
  { type: "land", classes: "land col13 row23 ocean-below ocean-left" },
  { type: "land", classes: "land col14 row23 " },
  { type: "land", classes: "land col15 row23 " },
  { type: "land", classes: "land col16 row23 " },
  { type: "land", classes: "land col17 row23 " },
  { type: "land", classes: "land col18 row23 ocean-above" },
  { type: "land", classes: "land col19 row23 ocean-above" },
  { type: "land", classes: "land col20 row23 ocean-above" },
  { type: "land", classes: "land col21 row23 ocean-above ocean-right" },
  { type: "ocean", classes: "ocean col22 row23 " },
  { type: "ocean", classes: "ocean col23 row23" },
  { type: "ocean", classes: "ocean col24 row23" },
  { type: "ocean", classes: "ocean col25 row23" },
  { type: "ocean", classes: "ocean col26 row23" },
  { type: "ocean", classes: "ocean col27 row23" },
  { type: "ocean", classes: "ocean col28 row23" },
  { type: "ocean", classes: "ocean col29 row23" },
  { type: "ocean", classes: "ocean col30 row23" },
  { type: "ocean", classes: "ocean col31 row23" },
  { type: "ocean", classes: "ocean col32 row23" },
  { type: "ocean", classes: "ocean col33 row23" },
  { type: "ocean", classes: "ocean col1 row24" },
  { type: "ocean", classes: "ocean col2 row24" },
  { type: "ocean", classes: "ocean col3 row24" },
  { type: "ocean", classes: "ocean col4 row24" },
  { type: "ocean", classes: "ocean col5 row24" },
  { type: "ocean", classes: "ocean col6 row24" },
  { type: "ocean", classes: "ocean col7 row24" },
  { type: "ocean", classes: "ocean col8 row24" },
  { type: "ocean", classes: "ocean col9 row24" },
  { type: "ocean", classes: "ocean col10 row24" },
  { type: "ocean", classes: "ocean col11 row24" },
  { type: "ocean", classes: "ocean col12 row24" },
  { type: "ocean", classes: "ocean col13 row24 " },
  { type: "land", classes: "land col14 row24 ocean-below ocean-left" },
  { type: "land", classes: "land col15 row24 ocean-below" },
  { type: "land", classes: "land col16 row24 ocean-below" },
  { type: "land", classes: "land col17 row24 ocean-below" },
  { type: "land", classes: "land col18 row24" },
  { type: "land", classes: "land col19 row24" },
  { type: "land", classes: "land col20 row24" },
  { type: "land", classes: "land col21 row24 ocean-right" },
  { type: "ocean", classes: "ocean col22 row24 " },
  { type: "ocean", classes: "ocean col23 row24" },
  { type: "ocean", classes: "ocean col24 row24" },
  { type: "ocean", classes: "ocean col25 row24" },
  { type: "ocean", classes: "ocean col26 row24" },
  { type: "ocean", classes: "ocean col27 row24" },
  { type: "ocean", classes: "ocean col28 row24" },
  { type: "ocean", classes: "ocean col29 row24" },
  { type: "ocean", classes: "ocean col30 row24" },
  { type: "ocean", classes: "ocean col31 row24" },
  { type: "ocean", classes: "ocean col32 row24" },
  { type: "ocean", classes: "ocean col33 row24" },
  { type: "ocean", classes: "ocean col1 row25" },
  { type: "ocean", classes: "ocean col2 row25" },
  { type: "ocean", classes: "ocean col3 row25" },
  { type: "ocean", classes: "ocean col4 row25" },
  { type: "ocean", classes: "ocean col5 row25" },
  { type: "ocean", classes: "ocean col6 row25" },
  { type: "ocean", classes: "ocean col7 row25" },
  { type: "ocean", classes: "ocean col8 row25" },
  { type: "ocean", classes: "ocean col9 row25" },
  { type: "ocean", classes: "ocean col10 row25" },
  { type: "ocean", classes: "ocean col11 row25" },
  { type: "ocean", classes: "ocean col12 row25" },
  { type: "ocean", classes: "ocean col13 row25" },
  { type: "ocean", classes: "ocean col14 row25" },
  { type: "ocean", classes: "ocean col15 row25" },
  { type: "ocean", classes: "ocean col16 row25" },
  { type: "ocean", classes: "ocean col17 row25" },
  { type: "land", classes: "land col18 row25 ocean-left" },
  { type: "land", classes: "land col19 row25" },
  { type: "land", classes: "land col20 row25" },
  { type: "land", classes: "land col21 row25 ocean-right" },
  { type: "ocean", classes: "ocean col22 row25" },
  { type: "ocean", classes: "ocean col23 row25" },
  { type: "ocean", classes: "ocean col24 row25" },
  { type: "ocean", classes: "ocean col25 row25" },
  { type: "ocean", classes: "ocean col26 row25" },
  { type: "ocean", classes: "ocean col27 row25" },
  { type: "ocean", classes: "ocean col28 row25" },
  { type: "ocean", classes: "ocean col29 row25" },
  { type: "ocean", classes: "ocean col30 row25" },
  { type: "ocean", classes: "ocean col31 row25" },
  { type: "ocean", classes: "ocean col32 row25" },
  { type: "ocean", classes: "ocean col33 row25" }
];

export default startingMap;
